import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:uuid/uuid.dart';

import '../../../data/models/task_model.dart';
import '../../../data/services/auth_service.dart';
import '../../../data/services/firestore_service.dart';
import '../../../data/services/subscription_service.dart';
import '../../../routes/app_pages.dart';
import '../models/ai_task_model.dart';
import '../services/copilot_service.dart';

class CopilotController extends GetxController {
  final CopilotService _copilotService = Get.find<CopilotService>();
  final FirestoreService _firestoreService = Get.find<FirestoreService>();
  final AuthService _authService = Get.find<AuthService>();
  final SubscriptionService _subscriptionService =
      Get.find<SubscriptionService>();
  final Uuid _uuid = const Uuid();

  final TextEditingController instructionController = TextEditingController();
  final RxBool isGenerating = false.obs;
  final RxBool isSaving = false.obs;
  final RxString errorMessage = ''.obs;
  final RxList<CopilotTaskPlan> generatedTasks = <CopilotTaskPlan>[].obs;

  bool get isPremium => _subscriptionService.isPremium.value;

  Future<void> generatePlan() async {
    final instruction = instructionController.text.trim();
    if (instruction.isEmpty) {
      Get.snackbar('Missing input', 'Describe your task or goal first.');
      return;
    }

    if (!isPremium) {
      Get.toNamed(Routes.SUBSCRIPTION);
      Get.snackbar(
        'Premium Required',
        'AI Copilot Automation is available only for premium subscribers.',
      );
      return;
    }

    isGenerating.value = true;
    errorMessage.value = '';
    try {
      final response = await _copilotService.generatePlan(instruction);
      if (response.requiresUpgrade) {
        Get.toNamed(Routes.SUBSCRIPTION);
        Get.snackbar('Premium Required', response.message);
        return;
      }

      if (!response.success || response.tasks.isEmpty) {
        final message =
            response.message.isEmpty
                ? 'Copilot could not generate a plan. Try adding more details.'
                : response.message;
        errorMessage.value = message;
        Get.snackbar('No plan generated', message);
        return;
      }

      generatedTasks.assignAll(response.tasks);
      Get.toNamed(Routes.COPILOT_PREVIEW);
    } catch (error) {
      _logControllerError('generatePlan', error);
      const message = 'Copilot request failed. Please try again.';
      errorMessage.value = message;
      Get.snackbar('Copilot failed', message);
    } finally {
      isGenerating.value = false;
    }
  }

  void applySuggestion(String text) {
    instructionController.text = text;
  }

  Future<void> updateTaskAt(
    int index, {
    required String title,
    required String description,
    required String deadline,
  }) async {
    if (index < 0 || index >= generatedTasks.length) {
      return;
    }

    generatedTasks[index] = generatedTasks[index].copyWith(
      title: title.trim(),
      description: description.trim(),
      deadline: deadline.trim(),
    );
    generatedTasks.refresh();
  }

  Future<void> saveGeneratedTasks() async {
    final userId = _authService.getUserId();
    if (userId == null) {
      Get.snackbar('Error', 'User not authenticated.');
      return;
    }

    if (generatedTasks.isEmpty) {
      Get.snackbar('No tasks', 'Generate a plan first.');
      return;
    }

    isSaving.value = true;
    try {
      for (final plan in generatedTasks) {
        final dueDate = _parseDeadline(plan.deadline);
        final reminderAt = dueDate.subtract(
          Duration(minutes: plan.reminderMinutesBefore.clamp(1, 1200)),
        );
        final executionType = _toExecutionType(plan.automation.executionType);
        final recipient = _extractRecipient(plan.automation.config);
        final recurrence = _toRecurrence(plan.repeat);

        final task = Task(
          id: '',
          title: plan.title,
          description: plan.description,
          category: 'AI Copilot',
          priority: 2,
          dueDate: dueDate,
          isCompleted: false,
          createdAt: DateTime.now(),
          userId: userId,
          notes: 'Generated by AI Copilot Automation',
          reminderEnabled: true,
          reminderAt: reminderAt,
          recurrence: recurrence,
          subtasks:
              plan.subtasks
                  .where((item) => item.trim().isNotEmpty)
                  .map((item) => SubTask(id: _uuid.v4(), title: item.trim()))
                  .toList(),
          autoExecute: plan.automation.enabled,
          executionType: executionType,
          recipient: recipient,
          automationInstruction: plan.automation.config.toString(),
          triggerBeforeDeadline: plan.automation.triggerBeforeDeadline,
          automationStatus:
              plan.automation.enabled
                  ? AutomationStatus.enabled
                  : AutomationStatus.disabled,
        );

        final saved = await _firestoreService.addTask(userId, task);

        // Persist nested automation object for copilot schema compatibility.
        await FirebaseFirestore.instance
            .collection('users')
            .doc(userId)
            .collection('tasks')
            .doc(saved.id)
            .set({
              'repeat': plan.repeat,
              'automation': plan.automation.toMap(),
            }, SetOptions(merge: true));
      }

      Get.offAllNamed(Routes.HOME);
      Get.snackbar('Plan saved', '${generatedTasks.length} task(s) created.');
      generatedTasks.clear();
      instructionController.clear();
    } catch (error) {
      _logControllerError('saveGeneratedTasks', error);
      Get.snackbar('Save failed', 'Unable to save tasks. Please try again.');
    } finally {
      isSaving.value = false;
    }
  }

  DateTime _parseDeadline(String raw) {
    final parsed = DateTime.tryParse(raw);
    if (parsed != null) {
      return parsed;
    }

    final now = DateTime.now();
    final normalized = raw.toLowerCase();
    if (normalized.contains('tomorrow')) {
      return DateTime(now.year, now.month, now.day + 1, 23, 59);
    }

    if (normalized.contains('friday')) {
      final daysUntilFriday = (DateTime.friday - now.weekday + 7) % 7;
      final dayOffset = daysUntilFriday == 0 ? 7 : daysUntilFriday;
      return DateTime(now.year, now.month, now.day + dayOffset, 17, 0);
    }

    return now.add(const Duration(hours: 24));
  }

  RecurrenceType _toRecurrence(String value) {
    switch (value.toLowerCase()) {
      case 'daily':
        return RecurrenceType.daily;
      case 'weekly':
        return RecurrenceType.weekly;
      case 'monthly':
        return RecurrenceType.monthly;
      default:
        return RecurrenceType.none;
    }
  }

  AutomationExecutionType _toExecutionType(String value) {
    switch (value.toLowerCase()) {
      case 'report':
        return AutomationExecutionType.report;
      case 'message':
        return AutomationExecutionType.message;
      case 'meeting':
        return AutomationExecutionType.meeting;
      default:
        return AutomationExecutionType.email;
    }
  }

  String _extractRecipient(Map<String, dynamic> config) {
    for (final key in ['recipientEmail', 'email', 'phoneNumber']) {
      final value = (config[key] ?? '').toString().trim();
      if (value.isNotEmpty) {
        return value;
      }
    }
    return '';
  }

  void _logControllerError(String operation, Object error) {
    Get.log('CopilotController.$operation failed: $error');
  }

  @override
  void onClose() {
    instructionController.dispose();
    super.onClose();
  }
}
