// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8HXtG4n7j55588WetcvV8ySWN5PeqSY',
    appId: '1:555243063404:web:3dabc96adba436e2f6f049',
    messagingSenderId: '555243063404',
    projectId: 'task-flow-4ce49',
    authDomain: 'task-flow-4ce49.firebaseapp.com',
    storageBucket: 'task-flow-4ce49.firebasestorage.app',
    measurementId: 'G-6KWBP59CXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRN4wQe1RfCrkXpL3oSx6F8IfD7p_Muuo',
    appId: '1:555243063404:android:615e887c6e44bff3f6f049',
    messagingSenderId: '555243063404',
    projectId: 'task-flow-4ce49',
    storageBucket: 'task-flow-4ce49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqqumaPYpTbD_Z9M6gPz4qaComnalcTHo',
    appId: '1:555243063404:ios:c3e605ad7620a2ccf6f049',
    messagingSenderId: '555243063404',
    projectId: 'task-flow-4ce49',
    storageBucket: 'task-flow-4ce49.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqqumaPYpTbD_Z9M6gPz4qaComnalcTHo',
    appId: '1:555243063404:ios:c3e605ad7620a2ccf6f049',
    messagingSenderId: '555243063404',
    projectId: 'task-flow-4ce49',
    storageBucket: 'task-flow-4ce49.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP8HXtG4n7j55588WetcvV8ySWN5PeqSY',
    appId: '1:555243063404:web:fa06a6ffbf4778d5f6f049',
    messagingSenderId: '555243063404',
    projectId: 'task-flow-4ce49',
    authDomain: 'task-flow-4ce49.firebaseapp.com',
    storageBucket: 'task-flow-4ce49.firebasestorage.app',
    measurementId: 'G-GL8XD0ZYYT',
  );
}
